# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: '/'
    customCommand: 'run clean:all'

- script: |
    npm run-script setup --plugins
  displayName: 'Launch Setup Strapi'

- checkout: self
  submodules: true